import { PageContent }  from '#components/page'

export const Page = () => {
    return (
        <PageContent>
            <section data-depth="1" id="ch13mod02_01"><h3 data-type="title">Intellectual Property Rights</h3>

<p id="fs-idp2974560">All patents and copyrights are scheduled to end someday. In 2003, copyright protection for Mickey Mouse was scheduled to run out. Once the copyright had expired, anyone would be able to copy Mickey Mouse cartoons or draw and sell new ones. In 1998, however, Congress passed the Sonny Bono Copyright Term Extension Act. For copyrights owned by companies or other entities, it increased or extended the copyright from 75 years to 95 years after publication. For copyrights owned by individuals, it increased or extended the copyright coverage from 50 years to 70 years after death. Along with protecting Mickey for another 20 years, the copyright extension affected about 400,000 books, movies, and songs.</p>
  <span className="os-caption">The number of applications filed for patents increased substantially beginning in the 1990s, due in part to the invention of the internet, which has led to many other inventions and to the 1998 Copyright Term Extension Act. (Source: http://www.uspto.gov/web/offices/ac/ido/oeip/taf/us_stat.htm)</span>
<p id="fs-idp3208736">While patents provide an incentive to innovate by protecting the innovator, they are not perfect. For example:</p>

<ul id="fs-idp77009328">
<li>In countries that already have patents, economic studies show that inventors receive only one-third to one-half of the total economic value of their inventions.</li>
<li>In a fast-moving high-technology industry like biotechnology or semiconductor design, patents may be almost irrelevant because technology is advancing so quickly.</li>
<li>Not every new idea can be protected with a patent or a copyright—for example, a new way of organizing a factory or a new way of training employees.</li>
<li>Patents may sometimes cover too much or be granted too easily. In the early 1970s, Xerox had received over 1,700 patents on various elements of the photocopy machine. Every time Xerox improved the photocopier, it received a patent on the improvement.</li>
<li>The 20-year time period for a patent is somewhat arbitrary. Ideally, a patent should cover a long enough period of time for the inventor to earn a good return, but not so long that it allows the inventor to charge a monopoly price permanently.</li>
</ul>

<p id="fs-idp48212800">Because patents are imperfect and do not apply well to all situations, alternative methods of improving the rate of return for inventors of new technology are desirable. The following sections describe some of these possible alternative policies.</p></section>


<section data-depth="1" id="ch13mod02_02"><h3 data-type="title">Policy #1: Government Spending on Research and Development</h3><p id="fs-idp2378928">If the private sector does not have sufficient incentive to carry out research and development, one possibility is for the government to fund such work directly. Government spending can provide direct financial support for research and development (R&amp;D) conducted at colleges and universities, nonprofit research entities, and sometimes by private firms, as well as at government-run laboratories. While government spending on research and development produces technology that is broadly available for firms to use, it costs taxpayers money and can sometimes be directed more for political than for scientific or economic reasons.</p>


<div data-type="note" data-has-label="true" id="ch13mod02_link01" className="economics linkup ui-has-child-title" data-label=""><header><h3 className="os-title" data-type="title">
  <span className="os-title-label">Link It Up</span>
</h3></header><section>
<div className="os-note-body">
<p id="fs-idp69402880">Visit the NASA <a href="http://openstax.org/l/NASA" target="_blank" rel="noopener nofollow">website</a> and the USDA <a href="http://openstax.org/l/USDA" target="_blank" rel="noopener nofollow">website</a> to read about government research that would not take place were it left to firms, due to the externalities.</p>

</div></section></div><p id="fs-idp35349296">The first column of <a href="13-2-how-governments-can-encourage-innovation#ch13mod02_tab05" className="autogenerated-content">Table 13.3</a> shows the sources of total U.S. spending on research and development. The second column shows the total dollars of R&amp;D funding by each source. The third column shows that, relative to the total amount of funding, 22.7% comes from the federal government, about 69% of R&amp;D is done by industry, and less than 4% is done by universities and colleges.  (The percentages below do not add up to exactly 100% due to rounding.)</p><div className="os-table" id="ch13mod02_tab05"><table data-id="ch13mod02_tab05"><thead>
<tr><th scope="col">Sources of R&amp;D Funding</th><th scope="col">Amount ($ billions)</th><th scope="col">Percent of the Total</th></tr>
</thead><tbody>
<tr><td><strong>Federal government</strong></td><td data-align="right"><strong>$129.6</strong></td><td data-align="right"><strong>21.4%</strong></td></tr>
<tr><td>Industry</td><td data-align="right">$426.0</td><td data-align="right">70.3%</td></tr>
<tr><td>Universities and colleges</td><td data-align="right">$20.7</td><td data-align="right">3.4%</td></tr>
<tr><td>Nonprofits</td><td data-align="right">$25.0</td><td data-align="right">4.1%</td></tr>
<tr><td>Nonfederal government</td><td data-align="right">$4.8</td><td data-align="right">0.8%</td></tr>
<tr><td><em data-effect="italics">Total</em></td><td data-align="right"><em data-effect="italics">$606.1</em></td><td></td></tr>
</tbody></table><div className="os-caption-container">
  <span className="os-title-label">Table </span>
  <span className="os-number">13.3</span>
  <span className="os-divider"> </span>
<span className="os-title" data-type="title">U.S. Research and Development Expenditures, 2018</span>

  <span className="os-divider"> </span>
<span className="os-caption">(Source: https://ncses.nsf.gov/pubs/nsf21324)</span>

</div>
</div><p id="fs-idp12116592">In the 1960s the federal government paid for about two-thirds of the nation’s R&amp;D. Over time, the U.S. economy has come to rely much more heavily on industry-funded R&amp;D. The federal government has tried to focus its direct R&amp;D spending on areas where private firms are not as active. One difficulty with direct government support of R&amp;D is that it inevitably involves political decisions about which projects are worthy. The scientific question of whether research is worthwhile can easily become entangled with considerations like the location of the congressional district in which the research funding is spent.</p></section>
</PageContent>
    )
}
