import { PageContent, Chat }  from '#components/page'

export const Page = () => {
    return (
        <PageContent>
<section data-depth="1" id="fs-idm27447296"><h3 data-type="title">Barter and the Double Coincidence of Wants</h3>
<p id="fs-idp21122880">To understand the usefulness of money, we must consider what the world would be like without money. How would people exchange goods and services? Economies without money typically engage in the barter system. <span data-type="term" id="term-00001" group-by="B">Barter</span>—literally trading one good or service for another—is highly inefficient for trying to coordinate the trades in a modern advanced economy. In an economy without money, an exchange between two people would involve a <span data-type="term" id="term-00002" group-by="d">double coincidence of wants</span>, a situation in which two people each want some good or service that the other person can provide. For example, if an accountant wants a pair of shoes, this accountant must find someone who has a pair of shoes in the correct size and who is willing to exchange the shoes for some hours of accounting services. Such a trade is likely to be difficult to arrange. Think about the complexity of such trades in a modern economy, with its extensive division of labor that involves thousands upon thousands of different jobs and goods.</p>
	<p id="fs-idp49478480">Another problem with the barter system is that it does not allow us to easily enter into future contracts for purchasing many goods and services. For example, if the goods are perishable it may be difficult to exchange them for other goods in the future. Imagine a farmer wanting to buy a tractor in six months using a fresh crop of strawberries. Additionally, while the barter system might work adequately in small economies, it will keep  these economies from growing. The time that individuals would otherwise spend producing goods and services and enjoying leisure time they spend bartering.</p></section>

<section data-depth="1" id="fs-idp67573392"><h3 data-type="title">Functions for Money</h3>

                <Chat subject="economics" topic="Defining Money by Its Functions" />

<p id="fs-idp107091424">Money solves the problems that the barter system creates. (We will get to its definition soon.) First, money serves as a <span data-type="term" id="term-00003" group-by="m">medium of exchange</span>, which means that money acts as an intermediary between the buyer and the seller. Instead of exchanging accounting services for shoes, the accountant now exchanges accounting services for money. The accountant then uses this  money to buy shoes. To serve as a medium of exchange, people must widely accept money as a method of payment in the markets for goods, labor, and financial capital.</p><p id="fs-idm128840144">Second, money must serve as a <span data-type="term" id="term-00004" group-by="s">store of value</span>. In a barter system, we saw the example of the shoemaker trading shoes for accounting services. However, she risks having her shoes go out of style, especially if she keeps them in a warehouse for future use—their value will decrease with each season. Shoes are not a good store of value. Holding money is a much easier way of storing value. You know that you do not need to spend it immediately because it will still hold its value the next day, or the next year. This function of money does not require that money is a <em data-effect="italics">perfect</em> store of value. In an economy with inflation, money loses some buying power each year, but it remains money.</p><p id="fs-idp49879088">Third, money serves as a <span data-type="term" id="term-00005" group-by="u">unit of account</span>, which means that it is the ruler by which  we measure values. For example, an accountant may charge $100 to file your tax return. That $100 can purchase two pair of shoes at $50 a pair. Money acts as a common denominator, an accounting method that simplifies thinking about trade-offs.</p><p id="fs-idp59807728">Finally, another function of money is that it must serve as a <span data-type="term" id="term-00006" group-by="s">standard of deferred payment</span>. This means that if money is usable today to make purchases, it must also be acceptable to make purchases today that the purchaser will pay in the <em data-effect="italics">future</em>. Loans and future agreements are stated in monetary terms and the standard of deferred payment is what allows us to buy goods and services today and pay in the future. Thus, <span data-type="term" id="term-00007" group-by="m">money</span> serves all of these functions— it is a medium of exchange, store of value, unit of account, and standard of deferred payment.</p></section>

        </PageContent>
    )
}
